ProjectManagement/Controllers/AsstDirectorController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProjectManagement.Controllers
{
  public class AsstDirectorController : Controller
    {
        public IActionResult Projects()
        {
            return View();
        }

        public IActionResult Reports()
        {
          return View();
        }
  }
} 

ProjectManagement/Controllers/DeptDirectorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ProjectManagement.Controllers
{
    public class DeptDirectorController : Controller
    {
    public IActionResult Projects()
    {
      return View();
    }

    public IActionResult Reports()
    {
      return View();
    }

  }
}

ProjectManagement/Controllers/ProjectManagerController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProjectManagement.Controllers
{
  public class ProjectManagerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AssignedProjects()
        {
          return View();
        }

        public IActionResult Reports()
        {
          return View();
        }

  }
}

ProjectManagement/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project Manangement</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link href="~/authcss/fontawesome-all.min.css" rel="stylesheet" />
    <link href="~/authcss/iofrm-style.css" rel="stylesheet" />
    <link href="~/authcss/iofrm-theme9.css" rel="stylesheet" />

</head>
<body>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/authjs/main.js"></script>
    <script src="~/authjs/popper.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>


    @RenderBody()

    @RenderSection("Scripts", required: false)
</body>
</html>

ProjectManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project Management</title>

    <environment include="Development">
        @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />*@
        <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css">


    </environment>
    <environment exclude="Development">
        <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css">
        @*<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" />*@
    </environment>
    
    <link rel="shortcut icon" href="~/favicon.ico">
    <link rel="icon" href="favicon.ico" type="image/x-icon">
    @*<link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css">*@
    <link href="~/css/material-design-iconic-font.min.css" rel="stylesheet" type="text/css">
    <link href="~/css/animate.css" rel="stylesheet" type="text/css">
    <link href="~/css/fancy-buttons.css" rel="stylesheet" type="text/css">
    <link href="~/css/filter.css" rel="stylesheet" type="text/css">
    <link href="~/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="~/css/lightgallery.css" rel="stylesheet" type="text/css">
    <link href="~/css/linea-icon.css" rel="stylesheet" type="text/css">
    <link href="~/css/pe-icon-7-stroke.css" rel="stylesheet" type="text/css">
    <link href="~/css/pe-icon-7-styles.css" rel="stylesheet" type="text/css">
    <link href="~/css/simple-line-icons.css" rel="stylesheet" type="text/css">
    <link href="~/css/themify-icons.css" rel="stylesheet" type="text/css">
    <link href="~/css/switchery.min.css" rel="stylesheet" type="text/css">
    <link href="~/css/owl.carousel.min.css" rel="stylesheet" type="text/css">
    <link href="~/css/owl.theme.default.min.css" rel="stylesheet" type="text/css">
    <link href="~/css/awesome-bootstrap-checkbox.css" rel="stylesheet" type="text/css">
    <link href="~/css/sweetalert.css" rel="stylesheet" />
    

    <link href="~/css/morris.css" rel="stylesheet" type="text/css" />
    <link href="~/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/jquery.toast.min.css" rel="stylesheet" type="text/css">
    <link href="~/css/style.css" rel="stylesheet" type="text/css">


</head>
<body>






    <environment include="Development">
        <script src="~/js/jquery.min.js"></script>
        @*<script src="~/lib/jquery/dist/jquery.js"></script>*@
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/jquery.min.js"></script>
        @*<script src="~/lib/jquery/dist/jquery.js"></script>*@
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        @*<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
            </script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
            </script>*@
    </environment>


    @*<script src="~/js/jquery.dataTables.min.js"></script>*@
    <script src="~/js/jquery.slimscroll.js"></script>
    <script src="~/js/moment.min.js"></script>
    <script src="~/js/jquery.simpleWeather.min.js"></script>
    <script src="~/js/simpleweather-data.js"></script>
    <script src="~/js/jquery.waypoints.min.js"></script>
    <script src="~/js/jquery.counterup.min.js"></script>
    <script src="~/js/dropdown-bootstrap-extended.js"></script>
    <script src="~/js/jquery.sparkline.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/Chart.min.js"></script>
    <script src="~/js/raphael.min.js"></script>
    <script src="~/js/morris.min.js"></script>
    <script src="~/js/morris.min.js"></script>
    <script src="~/js/jquery.toast.min.js"></script>
    <script src="~/js/switchery.min.js"></script>
    <script src="~/js/init.js"></script>
    <script src="~/js/sweetalert.min.js"></script>




    <script src="~/js/export-table-data.js"></script>
    <script src="~/js/datatables/media/js/jquery.dataTables.min.js"></script>
    <script src="~/js/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="~/js/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="~/js/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/js/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/js/pdfmake/build/pdfmake.min.js"></script>
    <script src="~/js/pdfmake/build/vfs_fonts.js"></script>





    <!-- Preloader -->
    <div class="preloader-it">
        <div class="la-anim-1"></div>
    </div>
    <!-- /Preloader -->
    <div class="wrapper pimary-color-green open-setting-panel theme-6-active">

        <div class="page-wrapper">
            <div class="container-fluid pt-25">
                @await Html.PartialAsync("_LayoutHeader")


                @await Html.PartialAsync("_ResellerLayoutAside")

                @RenderBody()

                @await Html.PartialAsync("_LayoutFooter")

            </div>
        </div>
    </div>

    @RenderSection("Scripts", required: false)

</body>
</html>

ProjectManagement/Views/Shared/_LayoutFooter.cshtml
<footer class="footer container-fluid pl-30 pr-30">
    <div class="row">
        <div class="col-sm-12">
            <p>2019 &copy; Wragby Business Solutions</p>
        </div>
    </div>
</footer>

ProjectManagement/Views/Shared/_LayoutHeader.cshtml
@using System.Linq
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Http.Authentication
@model LoginViewModel
@inject SignInManager<ApplicationUser> SignInManager

<!-- Top Menu Items -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="mobile-only-brand pull-left">
        <div class="nav-header pull-left">
            <div class="logo-wrap">
                <a asp-area="" asp-controller="Home" asp-action="Index">

                    <h5> <span style="color: forestgreen">Project Management</span></h5>
                </a>
            </div>
        </div>
        <a id="toggle_nav_btn" class="toggle-left-nav-btn inline-block ml-20 pull-left" href="javascript:void(0);"><i class="zmdi zmdi-menu"></i></a>
        <a id="toggle_mobile_search" data-toggle="collapse" data-target="#search_form" class="mobile-only-view" href="javascript:void(0);"><i class="zmdi zmdi-search"></i></a>
        <a id="toggle_mobile_nav" class="mobile-only-view" href="javascript:void(0);"><i class="zmdi zmdi-more"></i></a>
        <form id="search_form" role="search" class="top-nav-search collapse pull-left">
            @*<div class="input-group">
                <input type="text" name="example-input1-group2" class="form-control" placeholder="Search">
                <span class="input-group-btn">
                    <button type="button" class="btn  btn-default" data-target="#search_form" data-toggle="collapse" aria-label="Close" aria-expanded="true"><i class="zmdi zmdi-search"></i></button>
                </span>
            </div>*@
        </form>
    </div>
    <div id="mobile_only_nav" class="mobile-only-nav pull-right">
        <ul class="nav navbar-right top-nav pull-right">

            <li class="dropdown auth-drp">
                <a href="#" class="dropdown-toggle pr-0" data-toggle="dropdown"><img src="~/img/user1.png" alt="user_auth" class="user-auth-img img-circle" /><span class="user-online-status"></span></a>
                <ul class="dropdown-menu user-auth-dropdown" data-dropdown-in="flipInX" data-dropdown-out="flipOutX">
                    <li>
                        <a href="profile.html"><i class="zmdi zmdi-account"></i><span>Profile</span></a>
                    </li>

                    <li>
                        <a href="#"><i class="zmdi zmdi-settings"></i><span>Settings</span></a>
                    </li>
                    <li class="divider"></li>
                    <a>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        
                        <form class="form-inline" asp-action="Logout" asp-controller="Account" method="post">
                            <i class="zmdi zmdi-power"></i>
                            <button type="submit" class="btn">
                                <span>Log Out</span>
                            </button>
                        </form>
                        
                    }
                    </a>
                    @*<a href="#"><i class="zmdi zmdi-power"></i><span>Log Out</span></a>*@
                </ul>
            </li>
        </ul>
    </div>
</nav>
<!-- /Top Menu Items -->

ProjectManagement/Views/Shared/_LayoutProjectLogin.cshtml
<!doctype html>
<html class="no-js" lang="en">



<head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>@ViewData["Title"] -  Project Management </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="apple-touch-icon.html">
    <!-- Place favicon.ico in the root directory -->
    <link rel="stylesheet" href="~/css/vendor.css">
    <link rel="stylesheet" href="~/css/app.css">
   
</head>
<body>
    @RenderBody()
    
  
    <script src="~/js/vendor.js"></script>
    <script src="~/js/app.js"></script>

</body>
@RenderSection("Scripts", required: false)
</html>

ProjectManagement/Views/Shared/_ResellerLayoutAside.cshtml
<!-- Left Sidebar Menu -->
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService


<div class="fixed-sidebar-left">
    <ul class="nav navbar-nav side-nav nicescroll-bar">
        <li class="navigation-header">
            <span></span>
            <i class="zmdi zmdi-more"></i>
        </li>



        @*@if ((await AuthorizationService.AuthorizeAsync(User, "Admin")).Succeeded)
        {*@
            <li>
                <a asp-controller="Home" asp-action="Index"><div class="pull-left"><i class="zmdi zmdi-landscape mr-20"></i><span class="right-nav-text">Dashboard</span></div><div class="pull-right"></div><div class="clearfix"></div></a>
            </li>

            <li>
                <a asp-controller="Admin" asp-action="Projects"><div class="pull-left"><i class="zmdi zmdi-nature-people mr-20"></i><span class="right-nav-text">Projects</span></div><div class="pull-right"></div><div class="clearfix"></div></a>

            </li>

            <li>
                <a asp-controller="Admin" asp-action="Report"><div class="pull-left"><i class="zmdi zmdi-subway mr-20"></i><span class="right-nav-text">Reports</span></div><div class="pull-right"></div><div class="clearfix"></div></a>
            </li>

            <li>
                <a asp-controller="Admin" asp-action="Docs"><div class="pull-left"><i class="zmdi zmdi-collection-folder-image mr-20"></i><span class="right-nav-text">Document Repository</span></div><div class="pull-right"></div><div class="clearfix"></div></a>
            </li>
            @*<li>
                <a asp-controller="Admin" asp-action="Methodology"><div class="pull-left"><i class="zmdi zmdi-collection-folder-image mr-20"></i><span class="right-nav-text">Methodologies</span></div><div class="pull-right"></div><div class="clearfix"></div></a>
            </li>*@
        @*}*@

        @if ((await AuthorizationService.AuthorizeAsync(User, "PM")).Succeeded)
        {
            @*<li>

                <a asp-controller="ProjectManager" asp-action="Index"><div class="pull-left"><i class="zmdi zmdi-landscape mr-20"></i><span class="right-nav-text">PM Dashboard</span></div><div class="pull-right"></div><div class="clearfix"></div></a>
            </li>*@

            @*<li>
                <a asp-controller="ProjectManager" asp-action="AssignedProjects"><div class="pull-left"><i class="zmdi zmdi-nature-people mr-20"></i><span class="right-nav-text">Assigned Projects</span></div><div class="pull-right"></div><div class="clearfix"></div></a>

            </li>

            <li>
                <a asp-controller="ProjectManager" asp-action="PM Reports"><div class="pull-left"><i class="zmdi zmdi-subway mr-20"></i><span class="right-nav-text">PM Reports</span></div><div class="pull-right"></div><div class="clearfix"></div></a>
            </li>*@
        }

        @*@if ((await AuthorizationService.AuthorizeAsync(User, "Manager")).Succeeded)
        {
            <li>
                <a asp-controller="Manager" asp-action="Projects"><div class="pull-left"><i class="zmdi zmdi-nature-people mr-20"></i><span class="right-nav-text">Projects</span></div><div class="pull-right"></div><div class="clearfix"></div></a>

            </li>

            <li>
                <a asp-controller="Manager" asp-action="Reports"><div class="pull-left"><i class="zmdi zmdi-subway mr-20"></i><span class="right-nav-text">Reports</span></div><div class="pull-right"></div><div class="clearfix"></div></a>
            </li>

        }

        @if ((await AuthorizationService.AuthorizeAsync(User, "AssDir")).Succeeded)
        {

            <li>
                <a asp-controller="AsstDirector" asp-action="Projects"><div class="pull-left"><i class="zmdi zmdi-nature-people mr-20"></i><span class="right-nav-text">Projects</span></div><div class="pull-right"></div><div class="clearfix"></div></a>

            </li>

            <li>
                <a asp-controller="AsstDirector" asp-action="Reports"><div class="pull-left"><i class="zmdi zmdi-subway mr-20"></i><span class="right-nav-text">Reports</span></div><div class="pull-right"></div><div class="clearfix"></div></a>
            </li>

        }

        @if ((await AuthorizationService.AuthorizeAsync(User, "DepDir")).Succeeded)
        {

            <li>
                <a asp-controller="DeptDirector" asp-action="Projects"><div class="pull-left"><i class="zmdi zmdi-nature-people mr-20"></i><span class="right-nav-text">Projects</span></div><div class="pull-right"></div><div class="clearfix"></div></a>

            </li>

            <li>
                <a asp-controller="DeptDirector" asp-action="Reports"><div class="pull-left"><i class="zmdi zmdi-subway mr-20"></i><span class="right-nav-text">Reports</span></div><div class="pull-right"></div><div class="clearfix"></div></a>
            </li>

        }*@
    </ul>
</div>