ProjectManagement/Models/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectManagement.Models
{
    public class Project
    {
        [Key]
        public string Id { get; set; }
        public string ProjectName { get; set; }
        public DateTime PublishedDate { get; set; }
        public string ProjectId { get; set; }
        public decimal ProjectCost { get; set; }
        public string DocumentLink { get; set; }
        public DateTime DateUpdated { get; set; }
        public Divisions Division { get; set; }
        public Categories Category { get; set; }
        public Status Status { get; set; }
        public bool IsApproved { get; set; }
        public virtual ProjectPhase Phase { get; set; }
    }
}

ProjectManagement/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjectManagement.Data;

namespace ProjectManagement.Controllers
{
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Docs()
        {
            return View();
        }

        public IActionResult Projects()
        {
            return View();
        } public IActionResult ProjectDetails()
        {
            return View();
        }
         public IActionResult AddInternalProject()
        {
            var methods = _context.Methodologies.ToList();
            var selectList = new List<SelectListItem>
            {
                new SelectListItem { Text = "Custom ", Value = "0" }
            };
            foreach (var item in methods)
            {
                selectList.Add(new SelectListItem { Text = item.Name, Value = item.Id });

            }
            ViewBag.methods = selectList;

            return View();
        }

        public IActionResult Report()
        {
            return View();
        }

        public IActionResult ExternalProjects()
        {
            return View();
        }
        public IActionResult InternalProjects()
        {
            return View();
        }
        public IActionResult Methodology()
        {
            return View();
        }

    public IActionResult UpstreamRepo()
    {
      return View();
    }

    public IActionResult DownstreamRepo()
    {
      return View();
    }

    public IActionResult SheRepo()
    {
      return View();
    }

    public IActionResult ProcurementRepo()
    {
      return View();
    }

    public IActionResult ViewDetails()
    {
      return View();
    }

        public IActionResult AddTask()
        {
            return View();
        }

    }
}

ProjectManagement/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ProjectManagement.Data;
using ProjectManagement.Models;



namespace ProjectManagement.Controllers
{

    public class ProjectController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProjectController(ApplicationDbContext context)
        {
            _context = context;

        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddProject()
        {
            return View();
        }
         public IActionResult AddInternalProject()
        {
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddInternalProject(Project project)

        {
            project.PublishedDate = DateTime.Now;
            project.DateUpdated = DateTime.Now;
            if (ModelState.IsValid)
            {
                _context.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        public IActionResult ProjectDetails()
        {
            return View();
        }
    }
}

ProjectManagement/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ProjectManagement.Controllers
{
    public class ReportsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ProjectSegmentation()
        {
            return View();
        }

        public IActionResult ProjectRevenue()
        {
            return View();
        }
    }
}

ProjectManagement/Views/Admin/AddTask.cshtml
@{
    ViewData["Title"] = "AddTask";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Row -->
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default card-view">
            <div class="panel-heading">
                <div class="pull-left">
                    <h3 class="txt-dark">Create New Task</h3>
                    <h6 class="panel-title txt-dark">Basic Tasks Details</h6>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="panel-wrapper collapse in">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-12 col-xs-12">
                            <div class="form-wrap">
                                <form>
                                    <div class="form-group">
                                        <label class="control-label mb-10" for="exampleInputuname_1">Name</label>
                                        <div class="input-group">
                                            <div class="input-group-addon"><i class="icon-user"></i></div>
                                            <input type="text" class="form-control" id="exampleInputuname_1" placeholder="Name">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label mb-10" for="exampleInputEmail_1">Category</label>
                                        <div class="input-group">
                                            <div class="input-group-addon"><i class="icon-envelope-open"></i></div>
                                            <input type="text" class="form-control" id="exampleInputEmail_1" placeholder="Category">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label mb-10" for="exampleInputpwd_1">Project ID</label>
                                        <div class="input-group">
                                            <div class="input-group-addon"><i class="icon-lock"></i></div>
                                            <input type="text" class="form-control" id="exampleInputpwd_1" placeholder="Project ID">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label mb-10" for="exampleInputpwd_1">Assign Task</label>
                                        <div class="input-group">
                                            <div class="input-group-addon"><i class="icon-lock"></i></div>
                                            <input type="text" class="form-control" id="exampleInputpwd_1" placeholder="Assign Task">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div id="education_fields"></div>
                                        <div class="row">
                                            <div class="col-sm-6 nopadding">
                                                <label class="control-label " for="exampleInputpwd_42">Task Timeline Start Date</label>
                                                <div class="form-group">
                                                    <div class="input-group">
                                                        <input type="date" class="form-control" id="Schoolname" name="Schoolname[]" value="" placeholder=" Start Date">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-sm-3 nopadding">
                                                <label class="control-label mb-6" for="exampleInputpwd_42">task Timeline End Date</label>
                                                <div class="form-group">
                                                    <input type="date" class="form-control" id="Schoolname" name="Schoolname[]" value="" placeholder="End Date">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group mb-0">
                                        <a asp-action="ViewDetails" class="btn btn-success  mr-10">Submit</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- /Row -->
<br />
<br />
<br />
<br />

<br /><br />
<br />
<br />
<br />

<br />

ProjectManagement/Views/Admin/DownstreamRepo.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<div class="row">

    <div class="col-sm-12">

      <div>
        <h5>Document Library</h5>
        @*<a class="btn btn-primary" asp-controller="Project" asp-action="AddProject"> Add New </a>*@
      </div>
      <br />

        <div class="panel panel-default card-view">
            <div class="panel-wrapper collapse in">

                <div class="panel-body">

                    <div class="table-wrap">
                        <div class="table-responsive">
                            <table id="example" class="table table-hover display  pb-30">
                                <thead>
                                  <tr>
                                    <th>Name</th>
                                    <th>Category</th>
                                    <th>Published</th>
                                    <th>Memo ID</th>
                                    <th></th>
                                    
                                  </tr>
                                </thead>
                                <tfoot>
                                  <tr>
                                    <th>Name</th>
                                    <th>Category</th>
                                    <th>Published</th>
                                    <th>Memo ID</th>
                                    <th></th>

                                  </tr>
                                </tfoot>
                                <tbody>
                                  <tr>
                                    <td>Laying Of Pipes</td>
                                    <td>Internal Memo</td>
                                    <td>22-6-19</td>
                                    <td>ASP63GB</td>

                                    <td><button class="btn btn-primary">View Details</button></td>

                                  </tr>
                                  <tr>
                                    <td>Transportation Of Crude</td>
                                    <td>Approval</td>
                                    <td>27-5-19</td>
                                    <td>ASP63GB</td>

                                    <td><button class="btn btn-primary">View Details</button></td>

                                  </tr>
                                  <tr>
                                    <td>Maintenance of Vessels</td>
                                    <td>Approval</td>
                                    <td>23-06-19</td>
                                    <td>ASP37FB</td>
                                    <td><button class="btn btn-primary">View Details</button></td>
                                  </tr>
                                  <tr>
                                    <td>Renovations and Repairs</td>
                                    <td>Internal Memo</td>
                                    <td>31-05-19</td>
                                    <td>ASP28FB</td>
                                    <td><button class="btn btn-primary">View Details</button></td>
                                  </tr>



                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /Row -->

ProjectManagement/Views/Admin/ProcurementRepo.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<div class="row">

    <div class="col-sm-12">

      <div>
        <h5>Document Library</h5>
        @*<a class="btn btn-primary" asp-controller="Project" asp-action="AddProject"> Add New </a>*@
      </div>
      <br />

        <div class="panel panel-default card-view">
            <div class="panel-wrapper collapse in">

                <div class="panel-body">

                    <div class="table-wrap">
                        <div class="table-responsive">
                            <table id="example" class="table table-hover display  pb-30">
                                <thead>
                                  <tr>
                                    <th>Name</th>
                                    <th>Category</th>
                                    <th>Published</th>
                                    <th>Memo ID</th>
                                    <th></th>
                                    
                                  </tr>
                                </thead>
                                <tfoot>
                                  <tr>
                                    <th>Name</th>
                                    <th>Category</th>
                                    <th>Published</th>
                                    <th>Memo ID</th>
                                    <th></th>

                                  </tr>
                                </tfoot>
                                <tbody>
                                  <tr>
                                    <td>Laying Of Pipes</td>
                                    <td>Internal Memo</td>
                                    <td>22-6-19</td>
                                    <td>ASP63GB</td>

                                    <td><button class="btn btn-primary">View Details</button></td>

                                  </tr>
                                  <tr>
                                    <td>Transportation Of Crude</td>
                                    <td>Approval</td>
                                    <td>27-5-19</td>
                                    <td>ASP63GB</td>

                                    <td><button class="btn btn-primary">View Details</button></td>

                                  </tr>
                                  <tr>
                                    <td>Maintenance of Vessels</td>
                                    <td>Approval</td>
                                    <td>23-06-19</td>
                                    <td>ASP37FB</td>
                                    <td><button class="btn btn-primary">View Details</button></td>
                                  </tr>
                                  <tr>
                                    <td>Renovations and Repairs</td>
                                    <td>Internal Memo</td>
                                    <td>31-05-19</td>
                                    <td>ASP28FB</td>
                                    <td><button class="btn btn-primary">View Details</button></td>
                                  </tr>



                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /Row -->

ProjectManagement/Views/Admin/ProjectDetails.cshtml
@{
    ViewData["Title"] = "ProjectDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

ProjectManagement/Views/Admin/Projects.cshtml
@{
    ViewData["Title"] = "Project";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="row">

    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">

        <div class="panel panel-default card-view">
            <div class="panel-heading">
                <div class="pull-left">
                    <h6 class="panel-title txt-dark">Project Category</h6>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="panel-wrapper collapse in">
                <div class="panel-body row">
                    <div class="">
                        <div class="pl-15 pr-15 mb-15">
                            <div class="pull-left">
                                <i class="zmdi zmdi-collection-folder-image inline-block mr-10 font-16"></i>
                                <span class="inline-block txt-dark"><a asp-controller="Admin" asp-action="InternalProjects">Internal Projects</a></span>
                            </div>

                            <div class="clearfix"></div>
                        </div>
                        <hr class="light-grey-hr mt-0 mb-25" />
                        <div class="pl-15 pr-15 mb-15">
                            <div class="pull-left">
                                <i class="zmdi zmdi-collection-folder-image inline-block mr-10 font-16"></i>
                                <span class="inline-block txt-dark"><a asp-controller="Admin" asp-action="ExternalProjects">External Projects</a></span>
                            </div>

                            <div class="clearfix"></div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>




</div>

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br /><br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

<br />

ProjectManagement/Views/Admin/Report.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="row">
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">

        <div class="panel panel-default card-view">
            <div class="panel-heading">
                <div class="pull-left">
                    <h6 class="panel-title txt-dark">Project Category</h6>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="panel-wrapper collapse in">
                <div class="panel-body row">
                    <div class="">
                        <div class="pl-15 pr-15 mb-15">
                            <div class="pull-left">
                                <i class="zmdi zmdi-collection-folder-image inline-block mr-10 font-16"></i>
                                <span class="inline-block txt-dark"><a asp-area="" asp-controller="Reports" asp-action="ProjectRevenue">Project Revenue</a></span>
                            </div>

                            <div class="clearfix"></div>
                        </div>
                        <hr class="light-grey-hr mt-0 mb-25" />
                        <div class="pl-15 pr-15 mb-15">
                            <div class="pull-left">
                                <i class="zmdi zmdi-collection-folder-image inline-block mr-10 font-16"></i>
                                <span class="inline-block txt-dark"><a asp-area="" asp-controller="Reports" asp-action="ProjectSegmentation">Project Segmentation</a></span>
                            </div>

                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br /><br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

<br /><br />
<br />
<br />
<br />

<br />


@await Html.PartialAsync("_LayoutFooter")

ProjectManagement/Views/Admin/UpstreamRepo.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<div class="row">

    <div class="col-sm-12">

      <div>
        <h5>Document Library</h5>
        @*<a class="btn btn-primary" asp-controller="Project" asp-action="AddProject"> Add New </a>*@
      </div>
      <br />

        <div class="panel panel-default card-view">
            <div class="panel-wrapper collapse in">

                <div class="panel-body">

                    <div class="table-wrap">
                        <div class="table-responsive">
                            <table id="example" class="table table-hover display  pb-30">
                                <thead>
                                  <tr>
                                    <th>Name</th>
                                    <th>Category</th>
                                    <th>Published</th>
                                    <th>Memo ID</th>
                                    <th></th>
                                    
                                  </tr>
                                </thead>
                                <tfoot>
                                  <tr>
                                    <th>Name</th>
                                    <th>Category</th>
                                    <th>Published</th>
                                    <th>Memo ID</th>
                                    <th></th>

                                  </tr>
                                </tfoot>
                                <tbody>
                                  <tr>
                                    <td>Laying Of Pipes</td>
                                    <td>Internal Memo</td>
                                    <td>22-6-19</td>
                                    <td>ASP63GB</td>

                                    <td><button class="btn btn-primary">View Details</button></td>

                                  </tr>
                                  <tr>
                                    <td>Transportation Of Crude</td>
                                    <td>Approval</td>
                                    <td>27-5-19</td>
                                    <td>ASP63GB</td>

                                    <td><button class="btn btn-primary">View Details</button></td>

                                  </tr>
                                  <tr>
                                    <td>Maintenance of Vessels</td>
                                    <td>Approval</td>
                                    <td>23-06-19</td>
                                    <td>ASP37FB</td>
                                    <td><button class="btn btn-primary">View Details</button></td>
                                  </tr>
                                  <tr>
                                    <td>Renovations and Repairs</td>
                                    <td>Internal Memo</td>
                                    <td>31-05-19</td>
                                    <td>ASP28FB</td>
                                    <td><button class="btn btn-primary">View Details</button></td>
                                  </tr>



                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /Row -->

ProjectManagement/Views/Admin/ViewDetails.cshtml
@{
    ViewData["Title"] = "ViewDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">

    <div class="col-sm-12">

        @*<div>
            <a class="btn btn-primary" asp-controller="Admin" asp-action="AddInternalProject"> Add New </a>
        </div>*@
        <br />

        <div class="panel panel-default card-view">
            <div class="panel-wrapper collapse in">

                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-1">
                            <h4>Tasks</h4>
                        </div>
                        <div class="col-sm-3">
                            <a class="btn btn-primary" asp-controller="Admin" asp-action="AddTask"> Add New </a>
                        </div>
                        <div class="col-md-1">
                            <a class="btn btn-primary"> Gantt Chart </a>
                        </div>
                        <div class="col-md-1">
                            <a class="btn btn-primary"> Classic View </a>
                        </div>
                        <div class="col-md-1">
                            <a class="btn btn-primary"> Kanban </a>
                        </div>
                    </div>




                    <div class="table-wrap">
                        <div class="table-responsive">
                            <table id="example" class="table table-hover display  pb-30">
                                <thead>
                                    <tr>
                                        <th>Group</th>
                                        <th>task Summary</th>
                                        <th>project</th>
                                        <th>Assigned To</th>
                                        <th>Stage</th>
                                        @*<th>Date Updated</th>*@
                                        <th>Cost %</th>
                                        <th>Starting Date</th>
                                        <th>Ending Date</th>
                                        <th>Progress</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>Group</th>
                                        <th>task Summary</th>
                                        <th>project</th>
                                        <th>Assigned To</th>
                                        <th>Stage</th>
                                        @*<th>Date Updated</th>*@
                                        <th>Cost %</th>
                                        <th>Starting Date</th>
                                        <th>Ending Date</th>
                                        <th>Progress</th>

                                    </tr>
                                </tfoot>
                                <tbody>
                                    <tr>
                                        <td>Analysis</td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td><a href="#"></a></td>
                                        @*<td>27-6-19</td>*@
                                        <td></td>
                                        <td></td>
                                        @*<td>Planning</td>*@
                                        <td></td>

                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>MISTDO Protal Dev</td>
                                        <td>DBAS</td>
                                        <td>Demo User</td>
                                        <td>Analysis</td>
                                        @*<td>31-5-19</td>*@
                                        <td>2%</td>
                                        <td>09-01-2019</td>
                                        @*<td>Development</td>*@
                                        <td>09-01-2019</td>
                                        <td>20%</td>
                                    </tr>

                                    <tr>
                                        <td>Specification</td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td><a href="#"></a></td>
                                        @*<td>27-6-19</td>*@
                                        <td></td>
                                        <td></td>
                                        @*<td>Planning</td>*@
                                        <td></td>
                                        <td></td>
                                    </tr>

                                    <tr>
                                        <td></td>
                                        <td>MISTDO Protal Dev</td>
                                        <td>DBAS</td>
                                        <td>Demo User</td>
                                        <td>Specification</td>
                                        @*<td>31-5-19</td>*@
                                        <td>10.3%</td>
                                        <td>09-01-2019</td>
                                        @*<td>Development</td>*@
                                        <td>09-01-2019</td>
                                        <td>40%</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /Row -->
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />